site: Social Interaction Lab
site_tagline: Social Interaction Lab at Stanford University!
logo_image: images/icon.png
url: socialinteractionlab@github.io
baseurl:

collections:
  papers:
    output: true
    permalink: /papers/:title
  

  people:
    output: false
    permalink: /people/:slug
  

  news:
    output: true
    permalink: /news/:slug
  joining:
    output: true
    permalink: /joining/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -


markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"
